<?php

# CLASS OPTIONS

class knack_options{

	# CONSTRUCT
	public function __construct(){

		# INSERT DEFAULT OPTIONS
		$this->knack_add_default_options('initial');

	}

	# ADD DEFAULT DATA
	public function knack_add_default_options($load = 'update'){

		# DEFAULT ARRAY
        $signups = array(
            array(
                'email' => 'johndoe@gmail.com',
                'name' => 'John Doe',
            ),
        );

        $version = '1.0.0';

		$default = array(
			'settings' => array(
                'dashboard' => array( # DASHBOARD
                    '_label' => 'Dashboard',
                    '_slug' => 'dashboard',
                ),
                'general' => array( # GENERAL
                    '_label' => 'General Settings',
                    '_slug' => 'general-settings',
                    'favIcon' => '',
                    'toTop' => 'true',
                    'codeHead' => '',
                    'codeBody' => '',
                    'codeCss' => '',
                    'page_404_title' => 'Oops!',
                    'page_404_sub' => 'It looks like the page you are looking for is not here.',
                    'page_404_description' => 'Please feel free to browse the rest of our site.',
                    'page_404_button_text' => 'Back home',
                    'page_404_button_url' => '#',
                ),
                'styling' => array( # STYLING
                    '_label' => 'Styling',
                    '_slug' => 'styling',
                    'accents' => array(
                        array(
                            'title' => 'Accent #1',
                            'label' => 'accentone',
                            'color' => '#4A4A4A',
                        ),
                        array(
                            'title' => 'Accent #2',
                            'label' => 'accenttwo',
                            'color' => '#999999',
                        ),
                        array(
                            'title' => 'Accent #3',
                            'label' => 'accentthree',
                            'color' => '#BCBCBC',
                        ),
                        array(
                            'title' => 'Accent #4',
                            'label' => 'accentfour',
                            'color' => '#2B2B2B',
                        ),
                        array(
                            'title' => 'Accent #5',
                            'label' => 'accentfive',
                            'color' => '#999999',
                        ),
                        array(
                            'title' => 'Accent #6',
                            'label' => 'accentsix',
                            'color' => '#999999',
                        ),
                    ),
                    'buttons' => array(
                        array(
                            'title' => 'Buttons',
                            'slug' => 'buttons',
                            'opacity' => 1,
                            'background' => '#333333',
                            'backgroundHover' => '#DDDDDD',
                            'family' => 'Roboto',
                            'size' => '12',
                            'transform' => 'uppercase',
                            'spacing' => '2',
                            'weight' => '300',
                            'color' => '#DDDDDD',
                            'hoverColor' => '#333333',
                        ),
                        array(
                            'title' => 'Tags & Categories',
                            'slug' => 'tags',
                            'opacity' => 1,
                            'background' => '#333333',
                            'backgroundHover' => '#DDDDDD',
                            'family' => 'Roboto',
                            'size' => '12',
                            'transform' => 'uppercase',
                            'spacing' => '2',
                            'weight' => '300',
                            'color' => '#DDDDDD',
                            'hoverColor' => '#333333',
                        ),
                    ),
                ),
                'typography' => array( # TYPOGRAPHY
                    '_label' => 'Typography',
                    '_slug' => 'typography',
                    'fonts' => array(
                        array(
                            'label' => 'Body',
                            'slug' => 'body',
                            'family' => 'Roboto',
                            'weight' => '300',
                            'size' => '14',
                            'lineHeight' => '25',
                            'style' => 'normal',
                            'transform' => 'inherit',
                            'spacing' => 'normal',
                            'subset' => '',
                            'color' => '#666666',
                            'hoverColor' => '#666666',
                            'defaultStyling' => 'false',
                        ),
                        array(
                            'label' => 'Body URL',
                            'slug' => 'url',
                            'family' => 'Roboto',
                            'weight' => '300',
                            'size' => '14',
                            'lineHeight' => '25',
                            'style' => 'normal',
                            'transform' => 'inherit',
                            'spacing' => 'normal',
                            'subset' => '',
                            'color' => '#CCCCCC',
                            'hoverColor' => '#999999',
                            'defaultStyling' => 'false',
                        ),
                        array(
                            'label' => 'h1',
                            'slug' => 'h1',
                            'family' => 'Roboto',
                            'weight' => '300',
                            'size' => '30',
                            'lineHeight' => '30',
                            'style' => 'normal',
                            'transform' => 'uppercase',
                            'spacing' => '2',
                            'subset' => '',
                            'color' => '#333333',
                            'hoverColor' => '#333333',
                            'defaultStyling' => 'false',
                        ),
                        array(
                            'label' => 'h2',
                            'slug' => 'h2',
                            'family' => 'Roboto',
                            'weight' => '300',
                            'size' => '25',
                            'lineHeight' => '25',
                            'style' => 'normal',
                            'transform' => 'uppercase',
                            'spacing' => '2',
                            'subset' => '',
                            'color' => '#333333',
                            'hoverColor' => '#333333',
                            'defaultStyling' => 'false',
                        ),
                        array(
                            'label' => 'h3',
                            'slug' => 'h3',
                            'family' => 'Roboto',
                            'weight' => '300',
                            'size' => '20',
                            'lineHeight' => '20',
                            'style' => 'normal',
                            'transform' => 'inherit',
                            'spacing' => '1',
                            'subset' => '',
                            'color' => '#333333',
                            'hoverColor' => '#333333',
                            'defaultStyling' => 'false',
                        ),
                        array(
                            'label' => 'h4',
                            'slug' => 'h4',
                            'family' => 'Roboto',
                            'weight' => '300',
                            'size' => '18',
                            'lineHeight' => '20',
                            'style' => 'normal',
                            'transform' => 'uppercase',
                            'spacing' => '2',
                            'subset' => '',
                            'color' => '#333333',
                            'hoverColor' => '#333333',
                            'defaultStyling' => 'false',
                        ),
                        array(
                            'label' => 'h5',
                            'slug' => 'h5',
                            'family' => 'Roboto',
                            'weight' => '300',
                            'size' => '16',
                            'lineHeight' => '20',
                            'style' => 'normal',
                            'transform' => 'uppercase',
                            'spacing' => '1.5',
                            'subset' => '',
                            'color' => '#333333',
                            'hoverColor' => '#333333',
                            'defaultStyling' => 'false',
                        ),
                        array(
                            'label' => 'h6',
                            'slug' => 'h6',
                            'family' => 'Roboto',
                            'weight' => '300',
                            'size' => '14',
                            'lineHeight' => '20',
                            'style' => 'normal',
                            'transform' => 'inherit',
                            'spacing' => 'normal',
                            'subset' => '',
                            'color' => '#333333',
                            'hoverColor' => '#333333',
                            'defaultStyling' => 'false',
                        ),
                        array(
                            'label' => 'Archive Title',
                            'slug' => 'archive_title',
                            'family' => 'Roboto',
                            'weight' => '700',
                            'size' => '16',
                            'lineHeight' => '20',
                            'style' => 'normal',
                            'transform' => 'uppercase',
                            'spacing' => 'normal',
                            'subset' => '',
                            'color' => '#333333',
                            'hoverColor' => '#333333',
                            'defaultStyling' => 'false',
                        ),
                        array(
                            'label' => 'Archive Price',
                            'slug' => 'archive_price',
                            'family' => 'Roboto',
                            'weight' => '300',
                            'size' => '16',
                            'lineHeight' => '20',
                            'style' => 'normal',
                            'transform' => 'inherit',
                            'spacing' => 'normal',
                            'subset' => '',
                            'color' => '#333333',
                            'hoverColor' => '#333333',
                            'defaultStyling' => 'false',
                        ),
                        array(
                            'label' => 'Label',
                            'slug' => 'label',
                            'family' => 'Roboto',
                            'weight' => '300',
                            'size' => '16',
                            'lineHeight' => '20',
                            'style' => 'normal',
                            'transform' => 'inherit',
                            'spacing' => 'normal',
                            'subset' => '',
                            'color' => '#333333',
                            'hoverColor' => '#333333',
                            'defaultStyling' => 'false',
                        ),
                        array(
                            'label' => 'Footer Heading',
                            'slug' => 'footer_heading',
                            'family' => 'Roboto',
                            'weight' => '300',
                            'size' => '20',
                            'lineHeight' => '20',
                            'style' => 'normal',
                            'transform' => 'inherit',
                            'spacing' => 'normal',
                            'subset' => '',
                            'color' => '#FFFFFF',
                            'hoverColor' => '#FFFFFF',
                            'defaultStyling' => 'false',
                        ),
                        array(
                            'label' => 'Footer Content',
                            'slug' => 'footer_content',
                            'family' => 'Roboto',
                            'weight' => '300',
                            'size' => '14',
                            'lineHeight' => '20',
                            'style' => 'normal',
                            'transform' => 'inherit',
                            'spacing' => 'normal',
                            'subset' => '',
                            'color' => '#FFFFFF',
                            'hoverColor' => '#FFFFFF',
                            'defaultStyling' => 'false',
                        ),
                        array(
                            'label' => 'Add to Cart',
                            'slug' => 'add_to_cart',
                            'family' => 'Roboto',
                            'weight' => '300',
                            'size' => '14',
                            'lineHeight' => '20',
                            'style' => 'normal',
                            'transform' => 'uppercase',
                            'spacing' => 'normal',
                            'subset' => '',
                            'color' => '#FF688A',
                            'hoverColor' => '#FF0D43',
                            'defaultStyling' => 'false',
                        ),
                        array(
                            'label' => 'Navigation Center',
                            'slug' => 'navigation_center',
                            'family' => 'Roboto',
                            'weight' => '300',
                            'size' => '12',
                            'lineHeight' => '18',
                            'style' => 'normal',
                            'transform' => 'uppercase',
                            'spacing' => 'normal',
                            'subset' => '',
                            'color' => '#999999',
                            'hoverColor' => '#999999',
                            'defaultStyling' => 'false',
                        ),
                    ),
                ),
                'header' => array( # HEADER
                    '_label' => 'Header',
                    '_slug' => 'header',
                    'layout' => 'default',
                    'srcLogo' => '',
                    'altLogo' => '',
                    'stickyLogo' => '',
                    'mobileLogo' => '',
                    'optionAccount' => 'true',
                    'optionCart' => 'true',
                    'optionWishlist' => 'true',
                    'optionSearch' => 'true',
                    'mobileSwitch' => '768',
                    'eyebrowText' => 'SUBSCRIBE AND GET $20 OFF*',
                    'modal' => 'true',
                    'modalTitle' => 'SUBSCRIBE AND GET $20 OFF*',
                    'modalText' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                    'modalBg' => '',
                    'modalColor' => '',
                    'centerContent' => array(
                        array(
                            'title' => '1st Column',
                            'slug' => 'col_1',
                            'opacity' => 1,
                            'label' => 'Free Delivery',
                            'sub' => 'Order over $50',
                            'icon' => 'fa-check-circle ',
                        ),
                        array(
                            'title' => '2nd Column',
                            'slug' => 'col_2',
                            'opacity' => 1,
                            'label' => 'Free Return',
                            'sub' => 'Order over $50',
                            'icon' => 'fa-calendar ',
                        ),
                        array(
                            'title' => '3rd Column',
                            'slug' => 'col_3',
                            'opacity' => 1,
                            'label' => '100% Secure',
                            'sub' => 'Order over $50',
                            'icon' => 'fa-lock ',
                        ),
                    ),
                    'stylingOptions' => array(
                        array(
                            'title' => 'Primary Navigation',
                            'slug' => 'navigation_primary',
                            'opacity' => 1,
                            'background' => '#FFFFFF',
                            'family' => 'Roboto',
                            'size' => '14',
                            'logoHeight' => '14',
                            'style' => 'normal',
                            'transform' => 'uppercase',
                            'spacing' => '2',
                            'subset' => '',
                            'weight' => '500',
                            'color' => '#000000',
                            'hoverColor' => '#999999',
                        ),
                        array(
                            'title' => 'Sticky Navigation',
                            'slug' => 'navigation_sticky',
                            'opacity' => 1,
                            'background' => '#FFFFFF',
                            'family' => 'Roboto',
                            'size' => '14',
                            'logoHeight' => '14',
                            'style' => 'normal',
                            'transform' => 'uppercase',
                            'spacing' => '2',
                            'subset' => '',
                            'weight' => '500',
                            'color' => '#000000',
                            'hoverColor' => '#999999',
                        ),
                        array(
                            'title' => 'Dropdown Navigation',
                            'slug' => 'navigation_dropdown',
                            'opacity' => 1,
                            'background' => '#161616',
                            'family' => 'Roboto',
                            'size' => '14',
                            'lineHeight' => 16,
                            'style' => 'normal',
                            'transform' => 'uppercase',
                            'spacing' => 'normal',
                            'subset' => '',
                            'weight' => '500',
                            'color' => '#FFFFFF',
                            'hoverColor' => '#EEEEEE',
                        ),
                        array(
                            'title' => 'Mobile',
                            'slug' => 'navigation_mobile',
                            'opacity' => 1,
                            'background' => '#B2B2B2',
                            'family' => 'Roboto',
                            'size' => '14',
                            'lineHeight' => 16,
                            'style' => 'normal',
                            'transform' => 'uppercase',
                            'spacing' => 'normal',
                            'subset' => '',
                            'weight' => '500',
                            'color' => '#FFFFFF',
                            'hoverColor' => '#FFFFFF',
                        ),
                        array(
                            'title' => 'Eyebrow',
                            'slug' => 'navigation_eyebrow',
                            'opacity' => 1,
                            'background' => '#000000',
                            'family' => 'Roboto',
                            'size' => '12',
                            'lineHeight' => 11,
                            'style' => 'normal',
                            'transform' => 'normal',
                            'spacing' => 'normal',
                            'subset' => '',
                            'weight' => '300',
                            'color' => '#FFFFFF',
                            'hoverColor' => '#CCCCCC',
                        ),
                    ),
                ),
                'footer' => array( # HEADER
                    '_label' => 'Footer',
                    '_slug' => 'footer',
                    'layout' => 'full',
                    'footerLogo' => '',
                    'columnLayout' => 4,
                    'backgroundPrimary' => '#161616',
                    'backgroundSecondary' => '#000000',
                    'copyright' => 'true',
                    'copyrightText' => 'Copyright information goes here.',
                    'social' => 'true',
                ),
                'blog' => array( # BLOG
                    '_label' => 'Blog Settings',
                    '_slug' => 'blog-settings',
                    'layout' => 'standard',
                    'singleLayout' => 'standard',
                    'socialIcons' => 'true',
                    'tags' => 'true',
                    'categories' => 'true',
                    'author' => 'true',
                ),
                'woocommerce' => array( # WOOCOMMERCE
                    '_label' => 'WooCommerce',
                    '_slug' => 'woocommerce',
                    'shopLayout' => 'standard',
                    'nextPrev' => 'false',
                    'socialIcons' => 'true',
                    'accountIcons' => 'false',
                    'perPage' => '8',
                ),
                'social' => array( # SOCIAL
                    '_label' => 'Social',
                    '_slug' => 'social-settings',
                    'facebookId' => '',
                    'socialIcons' => 'true',
                    'socialPrimaryColor' => '#A9A9A9',
                    'socialItems' => array(
                        array(
                            'label' => 'facebook',
                            'status' => 'true',
                            'url' => '#',
                            'target' => '_blank',
                            'hoverColor' => '#FFFFFF',
                        ),
                        array(
                            'label' => 'twitter',
                            'status' => 'true',
                            'url' => '#',
                            'target' => '_blank',
                            'hoverColor' => '#FFFFFF',
                        ),
                        array(
                            'label' => 'google-plus',
                            'status' => 'true',
                            'url' => '#',
                            'target' => '_blank',
                            'hoverColor' => '#FFFFFF',
                        ),
                        array(
                            'label' => 'vimeo',
                            'status' => 'false',
                            'url' => '#',
                            'target' => '_blank',
                            'hoverColor' => '#FFFFFF',
                        ),
                        array(
                            'label' => 'dribbble',
                            'status' => 'false',
                            'url' => '#',
                            'target' => '_blank',
                            'hoverColor' => '#FFFFFF',
                        ),
                        array(
                            'label' => 'pinterest',
                            'status' => 'false',
                            'url' => '#',
                            'target' => '_blank',
                            'hoverColor' => '#FFFFFF',
                        ),
                        array(
                            'label' => 'youtube',
                            'status' => 'false',
                            'url' => '#',
                            'target' => '_blank',
                            'hoverColor' => '#FFFFFF',
                        ),
                        array(
                            'label' => 'tumblr',
                            'status' => 'false',
                            'url' => '#',
                            'target' => '_blank',
                            'hoverColor' => '#FFFFFF',
                        ),
                        array(
                            'label' => 'linkedin',
                            'status' => 'false',
                            'url' => '#',
                            'target' => '_blank',
                            'hoverColor' => '#FFFFFF',
                        ),
                        array(
                            'label' => 'rss',
                            'status' => 'false',
                            'url' => '#',
                            'target' => '_blank',
                            'hoverColor' => '#FFFFFF',
                        ),
                        array(
                            'label' => 'behance',
                            'status' => 'false',
                            'url' => '#',
                            'target' => '_blank',
                            'hoverColor' => '#FFFFFF',
                        ),
                        array(
                            'label' => 'instagram',
                            'status' => 'false',
                            'url' => '#',
                            'target' => '_blank',
                            'hoverColor' => '#FFFFFF',
                        ),
                        array(
                            'label' => 'flickr',
                            'status' => 'false',
                            'url' => '#',
                            'target' => '_blank',
                            'hoverColor' => '#FFFFFF',
                        ),
                    ),
                    'shares' => array(
                        array(
                            'status' => 'false',
                            'for' => 'Posts',
                            'postType' => 'post',
                            'socialItems' => array(
                                array(
                                    'label' => 'facebook',
                                    'description' => '',
                                    'status' => 'true',
                                ),
                                array(
                                    'label' => 'twitter',
                                    'description' => '',
                                    'status' => 'true',
                                ),
                                array(
                                    'label' => 'googleplus',
                                    'description' => '',
                                    'status' => 'true',
                                ),
                                array(
                                    'label' => 'pinterest',
                                    'description' => '',
                                    'status' => 'true',
                                ),
                            ),
                        ),
                        array(
                            'status' => 'false',
                            'for' => 'WooCommerce Single Product Page',
                            'postType' => 'product',
                            'socialItems' => array(
                                array(
                                    'label' => 'facebook',
                                    'description' => '',
                                    'status' => 'true',
                                ),
                                array(
                                    'label' => 'twitter',
                                    'description' => '',
                                    'status' => 'true',
                                ),
                                array(
                                    'label' => 'googleplus',
                                    'description' => '',
                                    'status' => 'true',
                                ),
                                array(
                                    'label' => 'pinterest',
                                    'description' => '',
                                    'status' => 'true',
                                ),
                            ),
                        ),
                    ),
                ),
                'signups' => array( # SIGNUPS
                    '_label' => 'Signups',
                    '_slug' => 'signup',
                ),
                'demo' => array( # DEMO
                    '_label' => 'Demo Install',
                    '_slug' => 'demo',
                ),
                'example' => array( # EXAMPLES
                    '_label' => 'Examples',
                    '_slug' => 'example',
                    'theme' => 'Knack Theme',
                    'logo' => '',
                    'text' => 'Text Example',
                    'check' => 'true',
                    'select' => '',
                    'color' => '#CCCCCC',
                ),
			),
		);

		if($load == 'initial'){

			# CREATE OPTION
			add_option( 'knack_theme_options', $default, '', 'yes' );
            add_option( 'knack_theme_signups', $signups, '', 'yes' );
            add_option( 'knack_theme_version', $version, '', 'yes' );

		} else {

			return $default;

		}

	}

}